### ISSUE TITLE
Metadata guard plugin allows renaming to protected string

### ISSUE THREAD

**Issue by AliceSLee** [irods/irods_rule_engine_plugin_metadata_guard#58]
- [x] main
- [x] 4-3-stable
---
### iRODS Version, OS and Version
iRODS 4.3.0; Ubuntu 20.04.6 LTS

### What did you try to do?
Using the metadata guard plugin, we protected a metadata prefix "teststring". 

### Expected behavior
1. Adding new metadata to an object with the protected prefix "teststring" in attribute name should fail. 
2. Removing or editing the "teststring" prefix on existing metadata should fail. 
3. Renaming existing metadata to have the protected prefix "teststring" in its new attribute name should fail. 

### Observed behavior 
1. and 2. above worked as expected, but in case 3, this activity was allowed (bypassing the guard). 

To reproduce:
- Setup protected string using metadata guard 
- Create data object and assign attribute that doesn't include the protected string
- imeta mod this data object to include the protected string at the start of the attribute name

**Comment by trel** [comment]
reopening - at least for discussion, so it doesn't disappear.

**Comment by korydraughn** [comment]
The metadata API uses the `arg0` to `argN` interface. The plugin does not check the target of a modification.

The plugin can be configured to allow only admins or approved editors to touch protected metadata.

Should users who do not satisfy the config requirements be able to overwrite protected metadata via a rename?

I don't think so.

**Comment by korydraughn** [comment]
That's correct.

Do you think that should be allowed?

My concern comes from whether it is possible to overwrite a protected AVU via a rename. I think you can.

**Comment by trel** [comment]
Oh... I see...

A) In addition to the arguable bug (the current discussion) where a non-admin/editor user can modify an existing AVU and put it INTO the protected namespace...

B) You are concerned that a non-admin/editor user can modify an existing non-protected AVU and OVERWRITE an already existing protected AVU... hmmm, that would definitely be worse and definitely be a bug.

Sounds like we have a couple tests to write.
