### ISSUE TITLE
iRODS version requirement

### ISSUE THREAD

**Issue by ll4strw** [irods/irods_rule_engine_plugin_metadata_guard#82]
I read in #76 about  iRODS version requirements and the recently implemented changes in the build system. However, if I try to build the metadata guard plugin on an ubuntu system in which iRODS comes straight from the apt package manager with version 4.3.1 (`irods-dev/jammy,now 4.3.1-0~jammy amd64 [installed]`), then the build fails with 
```
CMake Error at CMakeLists.txt:4 (find_package):
  Could not find a configuration file for package "IRODS" that is compatible
  with requested version "4.90.0".

  The following configuration files were considered but not accepted:

    /usr/lib/irods/cmake/IRODSConfig.cmake, version: 4.3.1
    /lib/irods/cmake/IRODSConfig.cmake, version: 4.3.1

```   
Shouldn't that succeed instead? After all, the requirements state <em>iRODS v4.3.0+</em>. Thanks.

**Comment by trel** [comment]
I believe what you're seeing is the development version (main branch) of this repository now requiring a development version of the irods-dev library that also reports as 4.90.0.

If you build the 4-3-1-stable branch of this repository, it should succeed to find/use the 4.3.1 released version of irods-dev.

**Comment by trel** [comment]
Excellent.   Closing.
