### ISSUE TITLE
Use of self.assertEquals breaks tests

### ISSUE THREAD

**Issue by FifthPotato** [irods/irods_rule_engine_plugin_metadata_guard#86]
- [x] main
- [x] 4-3-stable

---

On Ubuntu 24, the use of `self.assertEquals` causes tests to fail. Each usage should be replaced with `self.assertEqual`.
Relevant lines:
https://github.com/irods/irods_rule_engine_plugin_metadata_guard/blob/de01a5054123e3e2dc0425e9e2de8ad0c4e534b2/packaging/test_rule_engine_plugin_metadata_guard.py#L130-L131

https://github.com/irods/irods_rule_engine_plugin_metadata_guard/blob/de01a5054123e3e2dc0425e9e2de8ad0c4e534b2/packaging/test_rule_engine_plugin_metadata_guard.py#L165-L167

Same issue as https://github.com/irods/irods_rule_engine_plugin_logical_quotas/issues/118

**Comment by alanking** [comment]
@FifthPotato - Please checkbook and close if complete.
